import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/header';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-100 dark:bg-gray-900">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="container mx-auto px-4 max-w-6xl">
            <>
              <Header />
              {children}
            </>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
